version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
